"""snapshot inicial - todas as tabelas existentes

Revision ID: 4785bde49aeb
Revises: 
Create Date: 2026-03-02 17:54:56.623914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4785bde49aeb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diarias_historico_movimentacoes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_itinerario', sa.BigInteger(), nullable=False),
    sa.Column('id_etapa_anterior', sa.Integer(), nullable=True),
    sa.Column('id_etapa_nova', sa.Integer(), nullable=False),
    sa.Column('id_usuario_responsavel', sa.BigInteger(), nullable=True),
    sa.Column('data_movimentacao', sa.DateTime(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_etapa_nova'], ['diarias_etapas.id'], ),
    sa.ForeignKeyConstraint(['id_itinerario'], ['diarias_itinerario.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_responsavel'], ['sis_usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contratos_aditivo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('unique_aditivo'))

    op.drop_table('contratos_aditivo')
    op.drop_table('categoria_contrato')
    with op.batch_alter_table('class_fonte', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('codigo'))

    op.drop_table('class_fonte')
    op.drop_table('tipodocumento')
    with op.batch_alter_table('sis_detalhes_empenho', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uk_detalhe_solic'))

    op.drop_table('sis_detalhes_empenho')
    with op.batch_alter_table('etapas_contrato', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('unique_etapa'))

    op.drop_table('etapas_contrato')
    with op.batch_alter_table('reajustes_contrato', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('unique_reajuste'))

    op.drop_table('reajustes_contrato')
    op.drop_table('empenho_produtos')
    op.drop_table('processos')
    op.drop_table('ug')
    op.drop_table('pd_itens')
    with op.batch_alter_table('ugs_permitidas_contrato', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('unique_ug'))

    op.drop_table('ugs_permitidas_contrato')
    with op.batch_alter_table('catmat_classes', schema=None) as batch_op:
        batch_op.alter_column('hash_row',
               existing_type=mysql.CHAR(length=40),
               type_=sa.String(length=40),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_catmat_classe_grupo'))

    with op.batch_alter_table('catmat_grupos', schema=None) as batch_op:
        batch_op.alter_column('hash_row',
               existing_type=mysql.CHAR(length=40),
               type_=sa.String(length=40),
               existing_nullable=True)

    with op.batch_alter_table('catmat_itens', schema=None) as batch_op:
        batch_op.alter_column('hash_row',
               existing_type=mysql.CHAR(length=40),
               type_=sa.String(length=40),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_catmat_item_pdm'))

    with op.batch_alter_table('catmat_pdms', schema=None) as batch_op:
        batch_op.alter_column('hash_row',
               existing_type=mysql.CHAR(length=40),
               type_=sa.String(length=40),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_catmat_pdm_classe'))

    with op.batch_alter_table('catserv_classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_classe_grupo'))
        batch_op.drop_constraint(batch_op.f('fk_classe_grupo'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'catserv_grupos', ['codigo_grupo'], ['codigo_grupo'])

    with op.batch_alter_table('catserv_divisoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_divisao_secao'))
        batch_op.drop_constraint(batch_op.f('fk_divisao_secao'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'catserv_secoes', ['codigo_secao'], ['codigo_secao'])

    with op.batch_alter_table('catserv_grupos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_grupo_divisao'))
        batch_op.drop_constraint(batch_op.f('fk_grupo_divisao'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'catserv_divisoes', ['codigo_divisao'], ['codigo_divisao'])

    with op.batch_alter_table('catserv_servicos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_servico_classe'))
        batch_op.drop_index(batch_op.f('idx_servico_grupo'))
        batch_op.drop_constraint(batch_op.f('fk_servico_grupo'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_servico_classe'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'catserv_grupos', ['codigo_grupo'], ['codigo_grupo'])
        batch_op.create_foreign_key(None, 'catserv_classes', ['codigo_classe'], ['codigo_classe'])

    with op.batch_alter_table('class_subitemdespesa', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('ano',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('codigoTipoClassificador',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('nomeTipoClassificador',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('nomeClassificador',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('valoresClassificador1',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('valoresClassificador2',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('class_tipopatrimonial', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('ano',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('codigoTipoClassificador',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('nomeTipoClassificador',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('nomeClassificador',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('valoresClassificador1',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('valoresClassificador2',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.alter_column('tipo_contrato',
               existing_type=mysql.CHAR(length=2),
               type_=sa.String(length=2),
               existing_nullable=True)
        batch_op.alter_column('catmat_pdm_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='ID do PDM CATMAT (tipificação de material até nível PDM)',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_contrato_catserv_grupo'))
        batch_op.drop_index(batch_op.f('idx_contrato_tipo'))
        batch_op.drop_index(batch_op.f('idx_contratos_catmat_classe'))
        batch_op.drop_index(batch_op.f('idx_contratos_catmat_pdm'))
        batch_op.drop_index(batch_op.f('idx_contratos_catserv_classe'))
        batch_op.drop_constraint(batch_op.f('fk_contrato_tipo_execucao'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_contratos_natureza'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_contratos_categoria'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_contrato_centro_custo'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tipoexecucao', ['tipo_execucao_id'], ['id'])
        batch_op.create_foreign_key(None, 'catserv_grupos', ['catserv_grupo_id'], ['codigo_grupo'])
        batch_op.create_foreign_key(None, 'natdespesas', ['natureza_id'], ['id'])
        batch_op.create_foreign_key(None, 'catserv_classes', ['catserv_classe_id'], ['codigo_classe'])
        batch_op.create_foreign_key(None, 'sis_usuarios', ['tipificado_por'], ['id'])
        batch_op.create_foreign_key(None, 'centrodecusto', ['centro_de_custo_id'], ['id'])
        batch_op.drop_column('hash_contrato')
        batch_op.drop_column('last_checked')
        batch_op.drop_column('categoria_contrato_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('hash_fiscais')
        batch_op.drop_column('hash_aditivos')

    with op.batch_alter_table('diarias_cotacoes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cotacoes_contrato'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'contratos', ['contrato_codigo'], ['codigo'])

    with op.batch_alter_table('diarias_servidores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_cpf_unique'))
        batch_op.drop_index(batch_op.f('ix_diarias_servidores_cpf'))
        batch_op.create_index(batch_op.f('ix_diarias_servidores_cpf'), ['cpf'], unique=True)

    with op.batch_alter_table('empenho', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('valor',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('vlr',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_empenho_cod_contrato'))
        batch_op.drop_index(batch_op.f('idx_empenho_data_emissao'))

    with op.batch_alter_table('empenho_itens', schema=None) as batch_op:
        batch_op.alter_column('codigo',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('codigoUG',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('CodContrato',
               existing_type=mysql.BIGINT(),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_empenho_itens_CodContrato'))
        batch_op.drop_index(batch_op.f('idx_empenho_itens_Natureza'), mysql_length={'Natureza': 6})

    with op.batch_alter_table('estados', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)

    with op.batch_alter_table('execucoes', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('tipo',
               existing_type=mysql.CHAR(length=1),
               type_=sa.String(length=1),
               existing_nullable=False,
               existing_server_default=sa.text("'S'"))
        batch_op.drop_index(batch_op.f('idx_exec_vinculado'))
        batch_op.drop_index(batch_op.f('idx_execucoes_catmat'))
        batch_op.drop_index(batch_op.f('idx_execucoes_catserv'))
        batch_op.drop_index(batch_op.f('idx_execucoes_tipo'))
        batch_op.drop_constraint(batch_op.f('fk_execucoes_usuario'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sis_usuarios', ['usuario_id'], ['id'])
        batch_op.drop_column('codigo_natureza')
        batch_op.drop_column('cpf_user')
        batch_op.drop_column('ano')
        batch_op.drop_column('data_criacao')
        batch_op.drop_column('mes')

    with op.batch_alter_table('fiscais_contrato', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('unique_responsavel'))

    with op.batch_alter_table('itens_contrato', schema=None) as batch_op:
        batch_op.alter_column('descricao',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('tipo_item',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_ic_catmat'))
        batch_op.drop_index(batch_op.f('idx_ic_catserv'))
        batch_op.drop_constraint(batch_op.f('fk_itens_contrato_usuario'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sis_usuarios', ['usuario_id'], ['id'])
        batch_op.drop_column('cpf_user')
        batch_op.drop_column('categoria_id')

    with op.batch_alter_table('itens_vinculados', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=mysql.CHAR(length=1),
               type_=sa.String(length=1),
               comment=None,
               existing_comment='S=Serviço, M=Material',
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_iv_contrato'))
        batch_op.drop_index(batch_op.f('idx_iv_item_contrato'))
        batch_op.create_index(batch_op.f('ix_itens_vinculados_codigo_contrato'), ['codigo_contrato'], unique=False)

    with op.batch_alter_table('liquidacao', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('valor',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_liquidacao_codContrato'))
        batch_op.drop_index(batch_op.f('idx_liquidacao_data_emissao'))

    with op.batch_alter_table('municipios', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               nullable=False)
        batch_op.alter_column('regiao_economica',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)

    with op.batch_alter_table('ob', schema=None) as batch_op:
        batch_op.alter_column('valor',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_ob_cod_contrato'), mysql_length={'codContrato': 20})
        batch_op.drop_index(batch_op.f('idx_ob_cod_natureza'))
        batch_op.drop_index(batch_op.f('idx_ob_codigo_ug'), mysql_length={'codigoUG': 10})
        batch_op.drop_index(batch_op.f('idx_ob_data_emissao'))

    with op.batch_alter_table('pd', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('valor',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('valorTotalPD',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_pd_cod_contrato'))
        batch_op.drop_index(batch_op.f('idx_pd_data_emissao'))

    with op.batch_alter_table('saldo_contrato_item', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('saldo_contrato_item_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('saldo_contrato_item_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'saldo_contrato', ['saldo_contrato_id'], ['id'])
        batch_op.create_foreign_key(None, 'itens_vinculados', ['item_vinculado_id'], ['id'])

    with op.batch_alter_table('seimovimentacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seimovimentacao_protocolo_procedimento'), ['protocolo_procedimento'], unique=False)

    with op.batch_alter_table('sis_etapas_fluxo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uk_etapa_alias'))
        batch_op.drop_index(batch_op.f('uk_etapa_ordem'))
        batch_op.drop_column('descricao')

    with op.batch_alter_table('sis_historico_movimentacoes', schema=None) as batch_op:
        batch_op.alter_column('id_usuario_responsavel',
               existing_type=mysql.BIGINT(unsigned=True),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_hist_solic'))
        batch_op.drop_constraint(batch_op.f('fk_hist_solic'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sis_solicitacoes', ['id_solicitacao'], ['id'])

    with op.batch_alter_table('sis_saldo_empenho_contrato', schema=None) as batch_op:
        batch_op.alter_column('saldo',
               existing_type=mysql.DECIMAL(precision=20, scale=2),
               comment=None,
               existing_comment='Valor total somado da tabela empenho',
               existing_nullable=False)
        batch_op.alter_column('data',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Data e hora da captura do saldo',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('cod_contrato',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='Código do contrato limpo',
               existing_nullable=False)
        batch_op.alter_column('competencia',
               existing_type=mysql.VARCHAR(length=25),
               comment=None,
               existing_comment='Mês/Ano de referência (ex: Junho/2025)',
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_contrato_comp'))
        batch_op.drop_index(batch_op.f('idx_data'))

    with op.batch_alter_table('sis_solicitacoes', schema=None) as batch_op:
        batch_op.alter_column('etapa_atual_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('competencia',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=25),
               existing_nullable=True)
        batch_op.alter_column('status_geral',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text("'ABERTO'"))
        batch_op.alter_column('num_nl',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='Nota de Liquidação (Doc 420)',
               existing_nullable=True)
        batch_op.alter_column('num_pd',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='Programação de Desembolso (Doc 421)',
               existing_nullable=True)
        batch_op.alter_column('tempo_total',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_solic_contrato'))
        batch_op.drop_index(batch_op.f('idx_solic_user'))
        batch_op.drop_constraint(batch_op.f('fk_solic_contrato'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sis_status_empenho', ['status_empenho_id'], ['id'])
        batch_op.create_foreign_key(None, 'contratos', ['codigo_contrato'], ['codigo'])
        batch_op.drop_column('status_empenho')

    with op.batch_alter_table('solicitacaoempenho', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('id_solicitacao',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='Na imagem é ID_Contrato, mas refere-se ao ID da tabela sis_solicitacoes',
               existing_nullable=False)
        batch_op.alter_column('valor',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False,
               comment=None,
               existing_comment='Inputado pelo usuário')
        batch_op.alter_column('id_user',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='ID do usuário',
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_solic_empenho_solicitacao'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sis_solicitacoes', ['id_solicitacao'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacaoempenho', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_solic_empenho_solicitacao'), 'sis_solicitacoes', ['id_solicitacao'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('id_user',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='ID do usuário',
               existing_nullable=False)
        batch_op.alter_column('valor',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=15, scale=2),
               nullable=True,
               comment='Inputado pelo usuário')
        batch_op.alter_column('id_solicitacao',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='Na imagem é ID_Contrato, mas refere-se ao ID da tabela sis_solicitacoes',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('sis_solicitacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_empenho', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_solic_contrato'), 'contratos', ['codigo_contrato'], ['codigo'], onupdate='CASCADE')
        batch_op.create_index(batch_op.f('idx_solic_user'), ['id_usuario_solicitante'], unique=False)
        batch_op.create_index(batch_op.f('idx_solic_contrato'), ['codigo_contrato'], unique=False)
        batch_op.alter_column('tempo_total',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('num_pd',
               existing_type=mysql.VARCHAR(length=50),
               comment='Programação de Desembolso (Doc 421)',
               existing_nullable=True)
        batch_op.alter_column('num_nl',
               existing_type=mysql.VARCHAR(length=50),
               comment='Nota de Liquidação (Doc 420)',
               existing_nullable=True)
        batch_op.alter_column('status_geral',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'ABERTO'"))
        batch_op.alter_column('competencia',
               existing_type=sa.String(length=25),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('etapa_atual_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    with op.batch_alter_table('sis_saldo_empenho_contrato', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('idx_contrato_comp'), ['cod_contrato', 'competencia'], unique=False)
        batch_op.alter_column('competencia',
               existing_type=mysql.VARCHAR(length=25),
               comment='Mês/Ano de referência (ex: Junho/2025)',
               existing_nullable=False)
        batch_op.alter_column('cod_contrato',
               existing_type=mysql.VARCHAR(length=20),
               comment='Código do contrato limpo',
               existing_nullable=False)
        batch_op.alter_column('data',
               existing_type=mysql.DATETIME(),
               comment='Data e hora da captura do saldo',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('saldo',
               existing_type=mysql.DECIMAL(precision=20, scale=2),
               comment='Valor total somado da tabela empenho',
               existing_nullable=False)

    with op.batch_alter_table('sis_historico_movimentacoes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_hist_solic'), 'sis_solicitacoes', ['id_solicitacao'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_hist_solic'), ['id_solicitacao'], unique=False)
        batch_op.alter_column('id_usuario_responsavel',
               existing_type=mysql.BIGINT(unsigned=True),
               nullable=False)

    with op.batch_alter_table('sis_etapas_fluxo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', mysql.TEXT(), nullable=True))
        batch_op.create_index(batch_op.f('uk_etapa_ordem'), ['ordem'], unique=True)
        batch_op.create_index(batch_op.f('uk_etapa_alias'), ['alias'], unique=True)

    with op.batch_alter_table('seimovimentacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seimovimentacao_protocolo_procedimento'))

    with op.batch_alter_table('saldo_contrato_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('saldo_contrato_item_ibfk_1'), 'saldo_contrato', ['saldo_contrato_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('saldo_contrato_item_ibfk_2'), 'itens_vinculados', ['item_vinculado_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('pd', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_pd_data_emissao'), ['dataEmissao'], unique=False)
        batch_op.create_index(batch_op.f('idx_pd_cod_contrato'), ['codContrato'], unique=False)
        batch_op.alter_column('valorTotalPD',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('valor',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('ob', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_ob_data_emissao'), ['dataEmissao'], unique=False)
        batch_op.create_index(batch_op.f('idx_ob_codigo_ug'), ['codigoUG'], unique=False, mysql_length={'codigoUG': 10})
        batch_op.create_index(batch_op.f('idx_ob_cod_natureza'), ['codNatureza'], unique=False)
        batch_op.create_index(batch_op.f('idx_ob_cod_contrato'), ['codContrato'], unique=False, mysql_length={'codContrato': 20})
        batch_op.alter_column('valor',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    with op.batch_alter_table('municipios', schema=None) as batch_op:
        batch_op.alter_column('regiao_economica',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('liquidacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_liquidacao_data_emissao'), ['dataEmissao'], unique=False)
        batch_op.create_index(batch_op.f('idx_liquidacao_codContrato'), ['codContrato'], unique=False)
        batch_op.alter_column('valor',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('itens_vinculados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_vinculados_codigo_contrato'))
        batch_op.create_index(batch_op.f('idx_iv_item_contrato'), ['item_contrato_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_iv_contrato'), ['codigo_contrato'], unique=False)
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=1),
               type_=mysql.CHAR(length=1),
               comment='S=Serviço, M=Material',
               existing_nullable=False)

    with op.batch_alter_table('itens_contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cpf_user', mysql.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_itens_contrato_usuario'), 'sis_usuarios', ['usuario_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_ic_catserv'), ['catserv_servico_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_ic_catmat'), ['catmat_item_id'], unique=False)
        batch_op.alter_column('tipo_item',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('descricao',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               nullable=True)

    with op.batch_alter_table('fiscais_contrato', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_responsavel'), ['codigo_contrato', 'tipo', 'cpf'], unique=True)

    with op.batch_alter_table('execucoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mes', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('data_criacao', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('ano', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cpf_user', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('codigo_natureza', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_execucoes_usuario'), 'sis_usuarios', ['usuario_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_execucoes_tipo'), ['tipo'], unique=False)
        batch_op.create_index(batch_op.f('idx_execucoes_catserv'), ['catserv_servico_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_execucoes_catmat'), ['catmat_item_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_exec_vinculado'), ['item_vinculado_id'], unique=False)
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=1),
               type_=mysql.CHAR(length=1),
               existing_nullable=False,
               existing_server_default=sa.text("'S'"))
        batch_op.alter_column('data',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('estados', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('empenho_itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_empenho_itens_Natureza'), ['Natureza'], unique=False, mysql_length={'Natureza': 6})
        batch_op.create_index(batch_op.f('idx_empenho_itens_CodContrato'), ['CodContrato'], unique=False)
        batch_op.alter_column('CodContrato',
               existing_type=mysql.BIGINT(),
               nullable=True)
        batch_op.alter_column('codigoUG',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('codigo',
               existing_type=mysql.TEXT(),
               nullable=True)

    with op.batch_alter_table('empenho', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_empenho_data_emissao'), ['dataEmissao'], unique=False)
        batch_op.create_index(batch_op.f('idx_empenho_cod_contrato'), ['codContrato'], unique=False)
        batch_op.alter_column('vlr',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('valor',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('diarias_servidores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diarias_servidores_cpf'))
        batch_op.create_index(batch_op.f('ix_diarias_servidores_cpf'), ['cpf'], unique=False)
        batch_op.create_index(batch_op.f('idx_cpf_unique'), ['cpf'], unique=True)

    with op.batch_alter_table('diarias_cotacoes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_cotacoes_contrato'), 'contratos', ['contrato_codigo'], ['codigo'], ondelete='SET NULL')

    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash_aditivos', mysql.CHAR(length=40), nullable=True))
        batch_op.add_column(sa.Column('hash_fiscais', mysql.CHAR(length=40), nullable=True))
        batch_op.add_column(sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
        batch_op.add_column(sa.Column('categoria_contrato_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_checked', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.add_column(sa.Column('hash_contrato', mysql.CHAR(length=40), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_contrato_centro_custo'), 'centrodecusto', ['centro_de_custo_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_contratos_categoria'), 'categoria_contrato', ['categoria_contrato_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_contratos_natureza'), 'natdespesas', ['natureza_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_contrato_tipo_execucao'), 'tipoexecucao', ['tipo_execucao_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_contratos_catserv_classe'), ['catserv_classe_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_contratos_catmat_pdm'), ['catmat_pdm_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_contratos_catmat_classe'), ['catmat_classe_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_contrato_tipo'), ['tipo_contrato'], unique=False)
        batch_op.create_index(batch_op.f('idx_contrato_catserv_grupo'), ['catserv_grupo_id'], unique=False)
        batch_op.alter_column('catmat_pdm_id',
               existing_type=mysql.INTEGER(),
               comment='ID do PDM CATMAT (tipificação de material até nível PDM)',
               existing_nullable=True)
        batch_op.alter_column('tipo_contrato',
               existing_type=sa.String(length=2),
               type_=mysql.CHAR(length=2),
               existing_nullable=True)

    with op.batch_alter_table('class_tipopatrimonial', schema=None) as batch_op:
        batch_op.alter_column('valoresClassificador2',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('valoresClassificador1',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('nomeClassificador',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('nomeTipoClassificador',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('codigoTipoClassificador',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('ano',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('class_subitemdespesa', schema=None) as batch_op:
        batch_op.alter_column('valoresClassificador2',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('valoresClassificador1',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('nomeClassificador',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('nomeTipoClassificador',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('codigoTipoClassificador',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('ano',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('catserv_servicos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_servico_classe'), 'catserv_classes', ['codigo_classe'], ['codigo_classe'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_servico_grupo'), 'catserv_grupos', ['codigo_grupo'], ['codigo_grupo'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_servico_grupo'), ['codigo_grupo'], unique=False)
        batch_op.create_index(batch_op.f('idx_servico_classe'), ['codigo_classe'], unique=False)

    with op.batch_alter_table('catserv_grupos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_grupo_divisao'), 'catserv_divisoes', ['codigo_divisao'], ['codigo_divisao'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_grupo_divisao'), ['codigo_divisao'], unique=False)

    with op.batch_alter_table('catserv_divisoes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_divisao_secao'), 'catserv_secoes', ['codigo_secao'], ['codigo_secao'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_divisao_secao'), ['codigo_secao'], unique=False)

    with op.batch_alter_table('catserv_classes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_classe_grupo'), 'catserv_grupos', ['codigo_grupo'], ['codigo_grupo'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_classe_grupo'), ['codigo_grupo'], unique=False)

    with op.batch_alter_table('catmat_pdms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_catmat_pdm_classe'), ['codigo_classe'], unique=False)
        batch_op.alter_column('hash_row',
               existing_type=sa.String(length=40),
               type_=mysql.CHAR(length=40),
               existing_nullable=True)

    with op.batch_alter_table('catmat_itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_catmat_item_pdm'), ['codigo_pdm'], unique=False)
        batch_op.alter_column('hash_row',
               existing_type=sa.String(length=40),
               type_=mysql.CHAR(length=40),
               existing_nullable=True)

    with op.batch_alter_table('catmat_grupos', schema=None) as batch_op:
        batch_op.alter_column('hash_row',
               existing_type=sa.String(length=40),
               type_=mysql.CHAR(length=40),
               existing_nullable=True)

    with op.batch_alter_table('catmat_classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_catmat_classe_grupo'), ['codigo_grupo'], unique=False)
        batch_op.alter_column('hash_row',
               existing_type=sa.String(length=40),
               type_=mysql.CHAR(length=40),
               existing_nullable=True)

    op.create_table('ugs_permitidas_contrato',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('codigo_contrato', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('codigo_ug', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('data_atualizacao', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['codigo_contrato'], ['contratos.codigo'], name=op.f('ugs_permitidas_contrato_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('ugs_permitidas_contrato', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_ug'), ['codigo_contrato', 'codigo_ug'], unique=True)

    op.create_table('pd_itens',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('codigo', mysql.TEXT(), nullable=True),
    sa.Column('codigoUG', mysql.TEXT(), nullable=True),
    sa.Column('dataEmissao', mysql.TEXT(), nullable=True),
    sa.Column('codigoTipoClassificador', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('nomeTipoClassificador', mysql.TEXT(), nullable=True),
    sa.Column('nomeClassificador', mysql.TEXT(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ug',
    sa.Column('codigo', mysql.TEXT(), nullable=True),
    sa.Column('titulo', mysql.TEXT(), nullable=True),
    sa.Column('cnpj', mysql.TEXT(), nullable=True),
    sa.Column('codigoOrgao', mysql.TEXT(), nullable=True),
    sa.Column('sigla', mysql.TEXT(), nullable=True),
    sa.Column('tipoAdministracao', mysql.TEXT(), nullable=True),
    sa.Column('tipoUG', mysql.TEXT(), nullable=True),
    sa.Column('gestao', mysql.TEXT(), nullable=True),
    sa.Column('codigoPoder', mysql.TEXT(), nullable=True),
    sa.Column('nomePoder', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.TEXT(), nullable=True),
    sa.Column('codigoUf', mysql.TEXT(), nullable=True),
    sa.Column('nomeMunicipio', mysql.TEXT(), nullable=True),
    sa.Column('ano', mysql.BIGINT(), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('processos',
    sa.Column('protocolo_procedimento', mysql.TEXT(), nullable=True),
    sa.Column('idprocedimento', mysql.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('procedimentoformatado', mysql.TEXT(), nullable=True),
    sa.Column('iddocumento', mysql.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('documentoformatado', mysql.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('linkacesso', mysql.TEXT(), nullable=True),
    sa.Column('descricao', mysql.TEXT(), nullable=True),
    sa.Column('data', mysql.DATETIME(), nullable=True),
    sa.Column('serie_idserie', mysql.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('serie_nome', mysql.TEXT(), nullable=True),
    sa.Column('serie_aplicabilidade', mysql.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('unidadeelaboradora_idunidade', mysql.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('unidadeelaboradora_sigla', mysql.TEXT(), nullable=True),
    sa.Column('unidadeelaboradora_descricao', mysql.TEXT(), nullable=True),
    sa.Column('numero', mysql.TEXT(), nullable=True),
    sa.Column('tempo_execucao_segundos', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('obs', mysql.TEXT(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('empenho_produtos',
    sa.Column('id_empenho', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('codigoUG', mysql.TEXT(), nullable=True),
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('descricaoProdutoPPA', mysql.TEXT(), nullable=True),
    sa.Column('nomeProdutoGenerico', mysql.TEXT(), nullable=True),
    sa.Column('descricaoProdutoGenerico', mysql.TEXT(), nullable=True),
    sa.Column('unidadeFornecimentoGenerico', mysql.TEXT(), nullable=True),
    sa.Column('quantidadePrevista', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('quantidade', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('precoUnitario', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('precoTotal', mysql.DOUBLE(asdecimal=True), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('reajustes_contrato',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('codigo_contrato', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('codReajuste', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('numOriginal', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('numProcesso', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('dtReajuste', sa.DATE(), nullable=True),
    sa.Column('dtPublicacao', sa.DATE(), nullable=True),
    sa.Column('indexador', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('valorReajuste', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('objeto', mysql.TEXT(), nullable=True),
    sa.Column('data_atualizacao', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['codigo_contrato'], ['contratos.codigo'], name=op.f('reajustes_contrato_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('reajustes_contrato', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_reajuste'), ['codigo_contrato', 'codReajuste'], unique=True)

    op.create_table('etapas_contrato',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('codigo_contrato', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('codEtapa', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('dscEtapa', mysql.TEXT(), nullable=True),
    sa.Column('dataInicio', sa.DATE(), nullable=True),
    sa.Column('dataFim', sa.DATE(), nullable=True),
    sa.Column('valorEtapa', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('data_atualizacao', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['codigo_contrato'], ['contratos.codigo'], name=op.f('etapas_contrato_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('etapas_contrato', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_etapa'), ['codigo_contrato', 'codEtapa'], unique=True)

    op.create_table('sis_detalhes_empenho',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('id_solicitacao', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('numero_ne', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('saldo_anterior', mysql.DECIMAL(precision=15, scale=2), server_default=sa.text("'0.00'"), nullable=True),
    sa.Column('tipo_despesa', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_solicitacao'], ['sis_solicitacoes.id'], name=op.f('fk_detalhe_solic'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('sis_detalhes_empenho', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uk_detalhe_solic'), ['id_solicitacao'], unique=True)

    op.create_table('tipodocumento',
    sa.Column('IdSerie', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Nome', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Aplicabilidade', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('IdSerie'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('class_fonte',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('codigo', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('descricao', mysql.TEXT(), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('class_fonte', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('codigo'), ['codigo'], unique=True)

    op.create_table('categoria_contrato',
    sa.Column('descricao', mysql.TEXT(), nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cpf_user', mysql.TEXT(), nullable=True),
    sa.Column('usuario_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('editado_por', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['sis_usuarios.id'], name=op.f('fk_categoria_contrato_usuario'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('contratos_aditivo',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('codigo_contrato', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('codAditivo', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('numOriginal', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('numProcesso', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('dtVigenciaIni', sa.DATE(), nullable=True),
    sa.Column('dtVigenciaFim', sa.DATE(), nullable=True),
    sa.Column('dtPublicacao', sa.DATE(), nullable=True),
    sa.Column('valor', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('dataCelebracao', sa.DATE(), nullable=True),
    sa.Column('objeto', mysql.TEXT(), nullable=True),
    sa.Column('data_atualizacao', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['codigo_contrato'], ['contratos.codigo'], name=op.f('contratos_aditivo_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('contratos_aditivo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_aditivo'), ['codigo_contrato', 'codAditivo'], unique=True)

    op.drop_table('diarias_historico_movimentacoes')
    # ### end Alembic commands ###
